### ISSUE TITLE
Import Irrlicht 1.9

### ISSUE THREAD

**Issue by appgurueu** [minetest/irrlicht#1]
See https://github.com/zaki/irrlicht for example

**Comment by sfan5** [comment]
That mirror is outdated by the way.
If you download Irrlicht 1.9 from `svn://svn.code.sf.net/p/irrlicht/code/trunk` right now, Minetest will not compile and even if you fixed that it wouldn't start either (something about X11 is broken).

**Comment by nerzhul** [comment]
irrlicht 1.9 is not out. But yeah when we got a real release i will rebase the current code

**Comment by numberZero** [comment]
> irrlicht 1.9 is not out.

Android support is not out, either. But we use that, from the `ogl-es` branch. 12 years is perhaps too little for supporting reduced OpenGL versions well enough...

Anyway, in addition to #10 (PR to 1.8-based #9), I have a [combined branch](/numberZero/irrlicht). It includes changes from #9 and #10 but is based on 1.9/ogl-es. It includes more input handling fixes (which *can* in theory be backported onto #9 but...). It is built with CMake (works for GNU/Linux and Android at least). It works well on X11 and Android and as SDL-based, should work on other platforms as well.

To work with that Irrlicht branch, Minetest needs minimal changes. I have [a branch](/numberZero/minetest/tree/android-dev/) with these but it is not clean for a PR yet. It is not release-ready but playable (build system is not ready yet though, some dependencies need to be compiled and linked or copied into native/deps manually).

**Comment by sfan5** [comment]
The decision about #1 vs. #4 vs. #8 should be made soon because any work that is already done can and probably will cause merge conflicts when we pull new changes from Irrlicht in bulk.
So far the work pushed to master is easily replicated since it's mostly code removal.

**Comment by numberZero** [comment]
#8 is the best, it’s rock solid. Oh, it doesn’t support Android? NP, you will do that yourselves. Or #4, backport that from 1.9/ogles resolving all the merge conflicts and internal interface changes. No problem, you have enough people and time for that.

**Comment by numberZero** [comment]
#8 is the best, it’s rock solid. Last major change seems to be copyright update in 2012. Oh, it doesn’t support Android? NP, you will do that yourselves. Or drop the Android version, who ever plays it? It supports DirectX 8, that’s much more important. Hope they didn’t break compilation for Windows™ 98.

**Comment by sfan5** [comment]
Importing Irrlicht 1.9 and merging ogl-es into it looks like the only solution that is both future-proof and works everywhere we need it to work.

@minetest/engine Opinions please.

**Comment by v-rob** [comment]
I would put my vote in for Irrlicht 1.9 with ogl-es.  After all, we already use ogl-es for Android, and 1.9 only needs a few fixes in our codebase.  There is no point in staying with 1.8 forever, and any attempt to selectively pick things from 1.9, IrrlichtBAW, and other forks is certain to become a mess and simply takes too much time.

**Comment by rubenwardy** [comment]
I think 1.9-dev makes more sense than 1.8

**Comment by nerzhul** [comment]
go ahead for irrlicht 1.9-dev, we merge opengl es we clear old backends (hello DX 9) and we try to add what we want in the roadmap
We should also ensure this irrlicht version is C++11 compliant, else i may take a boring pass on it to clear :p

**Comment by sfan5** [comment]
[`master`](https://github.com/minetest/irrlicht/tree/master) is now based on Irrlicht's ogl-es development state.
As it turns out the ogl-es branch still supports normal OpenGL so we don't need to do any potentially complicated merging.

There's also [`svn-trunk`](https://github.com/minetest/irrlicht/tree/svn-trunk) and [`svn-ogl-es`](https://github.com/minetest/irrlicht/tree/svn-ogl-es) branches tracking upstream commits (only partial history from r6000 onward).
git-svn is unfortunately not stateless so I'll figure out an automation solution myself that automatically updates those two branches.
