### ISSUE TITLE
Unable to install irrlicht with cmake

### ISSUE THREAD

**Issue by sunnyEV** [minetest/irrlicht#109]
Hi,

 Trying to install irrlichtmt, 
I installed all the necessary libraries and exported the environmental variables in .bashrc. Still I'm end up in cmake error.

```
export PNG_LIBRARY=/home/sun/data/softwares/libpng-1.6.37/lib
export PNG_INCLUDE_DIR=/home/sun/data/softwares/libpng-1.6.37/include

export JPEG_INCLUDE_DIR=/home/sun/data/softwares/jpeg-9e/include
export JPEG_LIBRARY=/home/sun/data/softwares/jpeg-9e/lib

export ZLIB_INCLUDE_DIR=/home//sun/data/softwares/zlib-1.2.12/include
export ZLIB_LIBRARY=/home/sun/data/softwares/zlib-1.2.12/lib


X11_Xxf86vm_LIB # (which path is correct ? 1 or 2)
#1#
https://github.com/Almamu/linux-wallpaperengine/issues/1
#export X11_INCLUDE_DIR=/home/sun/data/softwares/libXxf86vm-1.1.4/lit/include
export X11_Xxf86vm_LIB=/home/sun/data/softwares/libXxf86vm-1.1.4/lit/lib

#2#
export LD_LIBRARY_PATH=/home/sun/data/softwares/libXxf86vm-1.1.4/lit/lib
export LD_RUN_PATH=/home/sun/data/softwares/libXxf86vm-1.1.4/lit/lib

I tried to build using the cmake . -DBUILD_SHARED_LIBS=OFF or cmake . && make
ending up same error. Need help!

-- *** Building IrrlichtMt 1.9.0 ***
-- Looking for IRR_COMPILE_WITH_OGLES1
-- Looking for IRR_COMPILE_WITH_OGLES1 - not found
-- Looking for IRR_COMPILE_WITH_OGLES2
-- Looking for IRR_COMPILE_WITH_OGLES2 - not found
-- Looking for IRR_COMPILE_WITH_OPENGL
-- Looking for IRR_COMPILE_WITH_OPENGL - found
-- Looking for IRR_LINUX_X11_XINPUT2
-- Looking for IRR_LINUX_X11_XINPUT2 - not found
-- Looking for IRR_COMPILE_WITH_SDL_DEVICE
-- Looking for IRR_COMPILE_WITH_SDL_DEVICE - not found
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_Xxf86vm_LIB (ADVANCED)
linked by target "IrrlichtMt" in directory /home/sun/data/softwares/reconcilation/minetest/lib/irrlichtmt/source/Irrlicht

-- Generating done
CMake Generate step failed. Build files cannot be regenerated correctly.
```

**Comment by rollerozxa** [comment]
I don't think CMake is able to use environment variables like that, you might need to pass them as CMake options like e.g. `-DPNG_LIBRARY=/home/sun/data/softwares/libpng-1.6.37/lib`

**Comment by rubenwardy** [comment]
Irrlichtmt is designed for our own usecases and we're not aiming to maintain compatibility with upstream irrlicht. It probably shouldn't be used by other projects

**Comment by sunnyEV** [comment]
Yes, you're right after setting environmental variable, cmake unable to find the lib. I dont really understand why it is showing this error message.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_Xxf86vm_LIB

**Comment by sunnyEV** [comment]
I tried to install in irrlichit in different server(SAGA). It says **Could NOT find OpenGLES2** 
I try to find OpenGLES2 LIb in web it says OpenGL or OpenGL-ES are not libraries 

> https://stackoverflow.com/questions/18996801/opengl-es-2-0-gldrawelements-implementation

Some help please.

cmake . -DBUILD_SHARED_LIBS=OFF

-- *** Building IrrlichtMt 1.9.0 ***
-- Looking for _IRR_COMPILE_WITH_OGLES1_
-- Looking for _IRR_COMPILE_WITH_OGLES1_ - found
-- Found OpenGLES: OPENGLES_LIBRARY-NOTFOUND
-- Looking for _IRR_COMPILE_WITH_OGLES2_
-- Looking for _IRR_COMPILE_WITH_OGLES2_ - found
CMake Error at /cluster/software/CMake/3.16.4-GCCcore-9.3.0/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  **Could NOT find OpenGLES2 (missing: OPENGLES2_LIBRARY OPENGLES2_INCLUDE_DIR)**
Call Stack (most recent call first):
  /cluster/software/CMake/3.16.4-GCCcore-9.3.0/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindOpenGLES2.cmake:24 (find_package_handle_standard_args)
  source/Irrlicht/CMakeLists.txt:73 (find_package)


-- Configuring incomplete, errors occurred!

**Comment by x2048** [comment]
The library is called `libGLESv2`. On a Debian system it would be part of `libgles-dev` package.

**Comment by AnotherNeko** [comment]
I installed libgles-dev but I still get the same error
`cmake . -DBUILD_SHARED_LIBS=OFF
-- *** Building IrrlichtMt 1.9.0 ***
-- Looking for _IRR_COMPILE_WITH_OGLES1_
-- Looking for _IRR_COMPILE_WITH_OGLES1_ - not found
-- Looking for _IRR_COMPILE_WITH_OGLES2_
-- Looking for _IRR_COMPILE_WITH_OGLES2_ - not found
-- Looking for _IRR_COMPILE_WITH_OPENGL_
-- Looking for _IRR_COMPILE_WITH_OPENGL_ - found
-- Looking for _IRR_LINUX_X11_XINPUT2_
-- Looking for _IRR_LINUX_X11_XINPUT2_ - not found
-- Looking for _IRR_COMPILE_WITH_SDL_DEVICE_
-- Looking for _IRR_COMPILE_WITH_SDL_DEVICE_ - not found
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_Xxf86vm_LIB (ADVANCED)
    linked by target "IrrlichtMt" in directory /home/kirrim/git/irrlicht/source/Irrlicht

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.`

**Comment by sfan5** [comment]
Like the error message hints at you have to install `libxxf86vm-dev` too.

Also note that you _can't_ set variables using the environment like the submitter tried to do, it has to be `-DNAME=value` on the CMake command line.
