### ISSUE TITLE
XInput2 causes erratic mouse behavior with two XScreens

### ISSUE THREAD

**Issue by scfarley** [minetest/irrlicht#131]
Following commit 91edd214aa0e8a5e9192a2fc9188a19fc5bf135e, the in-game mouse behavior became erratic where the mouse would 
attempt to control the move the view within the game on one screen but keep the cursor on a different screen.  However, this only happens on `:0.0`.

My system has two XScreens (`:0.0` and `:0.1`).  At any menu inside Minetest, there is no issue.  If I run the game on `:0.1`, there is also no issue.  The mouse stays with the game on the same screen and all is good.

If it is played on `:0.0`, then it is erratic.  The mouse is mostly seen on `:0.1`.  While dragging the mouse, the game flickers (painfully) a lot as it spins the view looking straight up.  It is as if something is confused about where the mouse should be in relation to the game window.  Could it be only considering the `display` and ignoring the `screen` (`:<display>[.screen]`) in making a decision about the mouse cursor?

I have tested Minetest 5.6.0 with IrrlichtMt 1.9.0mt7 with and without this commit so can confirm the issue is related to XInput2.

**Comment by sfan5** [comment]
see also https://github.com/minetest/minetest/issues/12697

**Comment by nPHYN1T3** [comment]
Be sure to denote 2 XScreens rather than 2 screens because this stuff gets confusing/misleading faster when you consider you can have more than one screen (monitor) on one XScreen ;)

**Comment by auouymous** [comment]
This was fixed by e9f205f952efac448974239526c5284134ae41b9.
