### ISSUE TITLE
Backport macOS fixes

### ISSUE THREAD

**Issue by MoNTE48** [minetest/irrlicht#14]
I will look like a parrot, but I will suggest once again taking macOS fixes from my Irrlicht fork.
Although some of them have already been merged with the official Irrlicht 1.9, not all fixes are merged yet. Here they are, in case anyone is interested:
https://github.com/MoNTE48/Irrlicht/commit/2681edb05866ea2fafc4d328ad18d8f5b95390dc
https://github.com/MoNTE48/Irrlicht/commit/d5302fc34872fed6ed7d2965b9be6b77f40a22f8
https://github.com/MoNTE48/Irrlicht/commit/1f82c0b38ed690347ef01d5535e7509b357a46a3

**Comment by sfan5** [comment]
Looks like we have all of these fixed by now.
