### ISSUE TITLE
IrrlichtMt target does not export SDL includes as PUBLIC

### ISSUE THREAD

**Issue by JosiahWI** [minetest/irrlicht#148]
It's just flat out incorrect, and it's kind of hilarious that it didn't break for anybody until now. `${SDL_INCLUDES}` should be added to the public include directories.

**Comment by sfan5** [comment]
Should it? I don't see any `SDL_*.h` referenced in the 'include' folder.

**Comment by JosiahWI** [comment]
This is only an issue if `source/CIrrDeviceSDL.h` is included anywhere in the public includes. I may have sounded a false alarm.

**Comment by JosiahWI** [comment]
I haven't looked in detail but I think this can be closed. Sorry about that.

**Comment by sfan5** [comment]
Okay.
