### ISSUE TITLE
Drop IrrCompileConfig in favor of proper CMake configuration

### ISSUE THREAD

**Issue by numberZero** [minetest/irrlicht#158]
`IrrCompileConfig.h` is a reminiscent of days before CMake. It was necessary for platform detection and for customization. Nowadays, CMake is a way better way for both.

Depends: minetest/minetest#13227

**Comment by sfan5** [comment]
Question is what even is there left to configure? video driver presence?

**Comment by numberZero** [comment]
numberZero/irrlicht#9. Does not apply well here yet due to line endings (see #161).
