### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/irrlicht#16]
To avoid confusion, I suggest to rename this thing to something unique.

I don't have any name suggestion myself, just any name that is not “Irrlicht” should work.

**Comment by v-rob** [comment]
If we do change the name, it should be obvious that it's Minetest's specific fork of Irrlicht, i.e. something obvious and clear like "MTIrrlicht".

**Comment by sfan5** [comment]
I think from the README it's sufficiently clear that this is not Irrlicht but our fork.
Or do you suggest changing some of the internal naming too (so that the file is called e.g. `libMtIrrlicht.so.1.9.0`)?

**Comment by Wuzzy2** [comment]
It is just better to give this baby a real and more or less unique name, otherwise you will have to refer to it in an awkward way like “our Irrlicht fork” or even worse, just “Irrlicht” (when it's actually not the real Irrlicht). IMHO there's no real excuse for maintaining this completely avoidable confusion.

But I don't think a rename needs to go all-in with literally renaming all the internal stuff as well, that would be overkill and will probably make backporting attempts very painful.

I think the rename can be just as simple as changing the repo name and how it's called in the README and maybe other highly visible files, while keeping most internal stuff like function names unchanged to avoid overkill.

On the other hand, when I think about it … `libMtIrrlicht.so.1.9.0` might actually be a good idea. Otherwise, how else would the system distinguish this fork from the real Irrlicht. This also begs the question, what should the user do if they want to install Minetest's Irrlicht fork along the real Irrlicht, when both are named exactly the same? Deliberately keeping the Irrlicht name unchanged for this fork seems like asking for trouble. ;-)
