### ISSUE TITLE
-Wtype-limits warnings in irrUString.h

### ISSUE THREAD

**Issue by Desour** [minetest/irrlicht#166]
I'm getting -Wtype-limits warnings in these lines:
https://github.com/minetest/irrlicht/blob/5527b9f373ef4267a2b44f816be07ddab48a289d/include/irrUString.h#L1373
https://github.com/minetest/irrlicht/blob/5527b9f373ef4267a2b44f816be07ddab48a289d/include/irrUString.h#L1474

If you cast a signed char (to compare), it's some negative number, and the comparison is always false.

Other lines may also be affected, i.e. wrong shifting.

I guess #33 introduced this. (cc @numberZero @sfan5)

Maybe using u8 instead of char would be better. But idk, hence this issue.

**Comment by numberZero** [comment]
In the calculations, it has to be `u8` (or `char8_t` but that’s C++20). But the API has to accept `char *`. So, cast. I think it is OK to cast pointers and not values (`unsigned char` is allowed to alias anything, and `u8` is `unsigned char`).

**Comment by numberZero** [comment]
Is ustring16 used anywhere actually? My grep suggests it isn’t.

**Comment by Desour** [comment]
Yes.
https://github.com/minetest/irrlicht/blob/5527b9f373ef4267a2b44f816be07ddab48a289d/include/irrUString.h#L3099
mtsrc/irrlicht_changes/CGUITTFont.h and mtsrc/irrlicht_changes/CGUITTFont.cpp use ustring.

**Comment by Desour** [comment]
But the function (`ustring16::append(const uchar8_t* const, u32)`) isn't called anywhere.
So, there's no bug in minetest because of this. And we could just remove the function. However, appending a utf8 string could be useful.

**Comment by bengardner** [comment]
The easiest way to see if a function is used in C++ is to comment it out (surround with #if 0/#endif) and do a clean build.
The append function that has the compile warning is not used.
