### ISSUE TITLE
Emscripten?

### ISSUE THREAD

**Issue by numberZero** [minetest/irrlicht#171]
Is it supported? There is enough Emscripten-specific code but no traces of autobuild or testing. I don’t want to keep the code blindly, not knowing whether I broke it inadvertently. There should either be a way to build and test it, or it should be eliminated, IMO.

**Comment by rubenwardy** [comment]
There's an unofficial web version of Minetest at  https://minetest.dustlabs.io/
@paradust7: would it help to keep the code, and can you test/maintain it?

**Comment by paradust7** [comment]
I haven't contributed anything upstream, all my changes are in my forks at https://github.com/paradust7.

Irrlicht already came with Emscripten support, but I had to replace portions of it, because not all of it was in working condition anyway. If you point me to specific sections, I can comment on it. The OpenGLES driver is the essential part.

**Comment by paradust7** [comment]
I wouldn't worry about breaking it. Whenever I pull and update (generally once every 3-4 months), I fix any new bugs or compile errors.

**Comment by numberZero** [comment]
Thanks. I’ll try to avoid excessive breakage, but expect some code flux. I’m working on new OpenGL drivers, including a ES 2 driver; see #160 for the details. The current code (#167) is incompatible with WebGL AFAIK but the OpenGL 3 *Core* driver I plan should be better (in the core profile, vertex and index data may only come from buffers, and also VAOs are mandatory; to my understanding, these are also the restrictions WebGL adds to GLES).

**Comment by numberZero** [comment]
One specific thing that seems strange for me is that `SDL_CreateWindowAndRenderer` seems to be called twice if window size is set to zero in CreationParams, first time from `createWindow`:
https://github.com/minetest/irrlicht/blob/5a79e1ae2bb0346e261152a21261af0531c2e4bf/source/Irrlicht/CIrrDeviceSDL.cpp#L392
And second time from `createDriver`:
https://github.com/minetest/irrlicht/blob/5a79e1ae2bb0346e261152a21261af0531c2e4bf/source/Irrlicht/CIrrDeviceSDL.cpp#L541-L544
That branch is *never* actually taken on other platforms IIUC.
