### ISSUE TITLE
When default to SDL?

### ISSUE THREAD

**Issue by numberZero** [minetest/irrlicht#206]
Basically, there are 2 options:
1. When the old device is dropped for a platform. Or,
2. Before that.

In either case, it should be done well before the next release. And in the case 2, it is also possible to revert the default before the release, e.g. if some unexpectedly hard issues are uncovered. Other than that, I see no point in waiting. Bug reports won’t appear until people will actually *use* it, on many very different systems.

**Comment by Desour** [comment]
I've used for some time now, and haven't encountered any issues that would legitimate holding back on defaulting to SDL.
So, let's just enable it now I guess.

**Comment by sfan5** [comment]
I support the "make sdl2 the default and remove the rest later" approach.
