### ISSUE TITLE
CPack Support

### ISSUE THREAD

**Issue by juozaspo** [minetest/irrlicht#21]
The CPack support information is missing from CMakeLists.txt. Trying to generate package (e.g. `cpack -G DEB`) results with an error. Also files generated by cpack should be listed in .gitignore file too. By this would mean users would be able to uninstall the (now renamed) library if needed.

**Comment by JosiahWI** [comment]
With the ponsible future goal of absorbing Irrlicht into Minetest, is this something that would be a productive effort? If this is a desirable enhancement, I may begin working on it, otherwise perhaps the issue could be closed?

**Comment by juozaspo** [comment]
As long as this becomes integrated into minetest in such a way there'll be no need for separate library installed to the system then that's good and as for now MT readme suggests copying it's sources to subdirectory inside the game source tree and the library is always built during game compilation.
