### ISSUE TITLE
MinGW dependencies

### ISSUE THREAD

**Issue by numberZero** [minetest/irrlicht#214]
Are scripts used to build MinGW dependencies available anywhere, like [those for Android](/minetest/minetest_android_deps)?

**Comment by rollerozxa** [comment]
I believe https://github.com/sfan5/mingw-pkgs/ is where sfan5 builds the dependencies from.

**Comment by sfan5** [comment]
Yep, these are just my private build scripts that I've been using for a while.
If necessary one day there are plenty of alternatives in the mingw world, such as msys packages: https://packages.msys2.org
