### ISSUE TITLE
SDL 2 on Windows: Minetest doesn't respect global display scaling setting

### ISSUE THREAD

**Issue by grorp** [minetest/irrlicht#217]
probably a duplicate of #173

----

Windows 10
Minetest commit minetest/minetest@25ef8f39341724550c3af19873e7f324a5a57251
IrrlichtMt commit 83699a835df2c7363ae856ee128fb2409743f65d

Windows has a global "display scaling" setting:
<img src="https://github.com/minetest/irrlicht/assets/82708541/571f47d5-625c-4777-9903-fbf2c035586d" alt="screenshot of the Windows 10 settings menu" height="200" />

Minetest with `USE_SDL2=FALSE` respects that setting (first screenshot taken with display scaling set to 100%, second one taken with display scaling set to 125%):  
<img src="https://github.com/minetest/irrlicht/assets/82708541/5964d5a9-4555-4469-841c-16bfa4409ca0" width="512" alt="no SDL2, global display scaling setting set to 100%" /> <img src="https://github.com/minetest/irrlicht/assets/82708541/eddc8f72-8676-468e-9d34-65d4922918e5" width="512" alt="no SDL2, global display scaling setting set to 125%" />

Minetest with `USE_SDL2=TRUE` doesn't respect it anymore (again first 100%, then 125%):  
<img src="https://github.com/minetest/irrlicht/assets/82708541/c7da3450-470a-4e6a-a2da-6de5571c87da" width="512" alt="SDL2, global display scaling setting set to 100%" /> <img src="https://github.com/minetest/irrlicht/assets/82708541/6c76d2e1-87cd-4b2f-bfa1-7e924f76f7c65" width="512" alt="SDL2, global display scaling setting set to 125%" />

**Comment by sfan5** [comment]
Yes, this is lack of high-dpi.
