### ISSUE TITLE
SDL 2 on Windows: Can't take screenshots in fullscreen mode

### ISSUE THREAD

**Issue by grorp** [minetest/irrlicht#218]
Windows 10
Minetest commit minetest/minetest@25ef8f39341724550c3af19873e7f324a5a57251
IrrlichtMt commit 83699a835df2c7363ae856ee128fb2409743f65d

With `USE_SDL2=FALSE`, I can take screenshots in fullscreen mode. Here's an example:

![fullscreen screenshot without sdl2](https://github.com/minetest/irrlicht/assets/82708541/49b3aa46-86e6-4178-accc-f39df09b416e)

With `USE_SDL2=TRUE`, when I take a screenshot in fullscreen mode, it looks like this:

![fullscreen screenshot with sdl2](https://github.com/minetest/irrlicht/assets/82708541/7c28d42c-be21-49d6-872e-0e5d6afb6210)

**Comment by NathanSalapat** [comment]
Maybe a stupid question but is this using the system screenshot function or Minetest's screenshot?

**Comment by Desour** [comment]
Could not reproduce on X11 with SDL. The minetest screenshot also doesn't work in mainmenu for me.

**Comment by grorp** [comment]
This is about Windows' built-in screenshot tool that is triggered when pressing <kbd>Win</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd>. Sorry for not being specific.

Interestingly, everything is fine if I take a screenshot of Minetest in fullscreen mode by launching Windows' built-in "Snipping Tool" or "Snip & Sketch" apps manually. (By pressing the <kbd>Win</kbd> key to temporarily escape fullscreen and start the respective app. Doing so makes the screen go black temporarily, see below.)

Another thing I can observe is that the screen goes black for quarter a second or so when Minetest enters or leaves fullscreen. It almost seems like Minetest is changing the monitor resolution, but that shouldn't be the case judging by the code. The screen also goes black for a short time when entering or exiting fullscreen with SDL disabled, though.

Unfortunately, I cannot make a screen recording of the issue because running a screen recorder makes the issue go away.

This issue isn't present for me on Linux/X11 either.

**Comment by Desour** [comment]
You could try to replace `SDL_WINDOW_FULLSCREEN_DESKTOP` with `SDL_WINDOW_FULLSCREEN` in `CIrrDeviceSDL.(h|cpp)` and see it that changes anything.

**Comment by grorp** [comment]
> You could try to replace `SDL_WINDOW_FULLSCREEN_DESKTOP` with `SDL_WINDOW_FULLSCREEN` in `CIrrDeviceSDL.(h|cpp)` and see it that changes anything.

Uh oh, now it's *actually* changing the monitor resolution. And <kbd>Win</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd> is still broken, but only sometimes (?).
