### ISSUE TITLE
Fix copy/paste issue on Linux platforms

### ISSUE THREAD

**Issue by zeuner** [minetest/irrlicht#25]
The long existing copy/paste issues of Minetest on Linux platforms have already been identified as an Irrlicht issue (see https://github.com/minetest/minetest/issues/7830 ). So here would be the place to fix it.

There have already been efforts to fix the issue on Irrlicht 1.8.4, which can be found in the https://github.com/edo9300/irrlicht1-8-4 repository, mostly in the commits from March 2020. Examples for relevant commits would be https://github.com/edo9300/irrlicht1-8-4/commit/f4a3f9a4fddf1b05eb6fc9988adbb5f24156afec , https://github.com/edo9300/irrlicht1-8-4/commit/d1584400f918397b1c4edaefa35a69a93a49bdac and https://github.com/edo9300/irrlicht1-8-4/commit/714022e32a1846665e09a524d3dff3df5b639b07 ). I can confirm that copy/paste on Linux platforms can successfully be done using the Irrlicht version from that repository, although I had to change some string types from UTF8 to wide strings. For copying from Minetest to other applications, I had to use a wrapper because Minetest/Irrlicht served the clipboard selection requests only for a very short timeframe.

Maybe this existing work can be ported to the Minetest Irrlicht fork in order to solve the copy/paste issues.

**Comment by JosiahWI** [comment]
Is there a part of this issue that wasn't fixed by #55?
