### ISSUE TITLE
Invalid comparator: vector3df/vector2df operator<

### ISSUE THREAD

**Issue by JosiahWI** [minetest/irrlicht#266]
```cpp
#define CATCH_CONFIG_MAIN
#include <catch.hpp>
#include <irrlicht.h>

#include <cmath>

TEST_CASE()
{
        irr::video::S3DVertex a;
        irr::video::S3DVertex b;
        a.Pos = irr::core::vector3df{0.0125, 0.0f, 0.0f};
        b.Pos = irr::core::vector3df{0.0126, 0.0f, 0.0f};
        CHECK(a != b);
        CHECK(a < b);
        CHECK(!(b < a));
}
```
![image](https://github.com/minetest/irrlicht/assets/41302989/485b6bd5-99e3-4cc8-aa15-e99ba3875ee1)

This is the cause of minetest/minetest#14132.

**Comment by sfan5** [comment]
Where's the bug here?

**Comment by JosiahWI** [comment]
a == b, a < b, and b < a are all true at the same time. That doesn't make any sense, and it leads to incorrect sorting logic when used in STL containers.

**Comment by JosiahWI** [comment]
I take that back. This is the correct result of the test.
