### ISSUE TITLE
Android build broken due to CMake

### ISSUE THREAD

**Issue by sfan5** [minetest/irrlicht#27]
<pre>-- The CXX compiler identification is Clang 11.0.5
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: [...]/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- *** Building IrrlichtMt 1.9.0 ***
-- Found ZLIB: [...]/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/16/libz.so (found version "1.2.11") 
-- Found JPEG: [...]/libjpeg/armeabi-v7a/opt/libjpeg-turbo/lib32/libjpeg.a (found version "62") 
-- Found PNG: [...]/libpng/armeabi-v7a/usr/local/lib/libpng.a (found version "1.6.37") 
-- Looking for _IRR_COMPILE_WITH_OGLES1_
-- Looking for _IRR_COMPILE_WITH_OGLES1_ - found
-- Found OpenGLES: [...]/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/16/libGLESv1_CM.so
-- Looking for _IRR_COMPILE_WITH_OGLES2_
-- Looking for _IRR_COMPILE_WITH_OGLES2_ - not found
-- Looking for _IRR_COMPILE_WITH_OPENGL_
-- Looking for _IRR_COMPILE_WITH_OPENGL_ - not found
-- The C compiler identification is Clang 11.0.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: [...]/llvm/prebuilt/linux-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
CMake Error: install(EXPORT "IrrlichtMt-export" ...) includes target "IrrlichtMt" which requires target "native_app_glue" that is not in any export set.
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.</pre>

@JosiahWI

**Comment by sfan5** [comment]
Judging by https://stackoverflow.com/questions/5378528/install-export-problem-for-shared-lib-with-dependencies CMake does not seem to offer a solution to the "static transitive dependency doesn't need to be exported" problem. Great.

**Comment by JosiahWI** [comment]
Exporting a target that links to a target should not error. I don't think I fully understand the issue here. There should be a dependency requirement in the Config.in file, because the target IrrlichtMt depends on needs to be found to load the exported IrrlichtMt target.

**Comment by JosiahWI** [comment]
Ah that library is added by us. I missed that so I'm responsible for the bug, I can PR a fix that target to the export.

**Comment by sfan5** [comment]
No need to bother with a PR, I can commit and test the fix if you tell me what needs to be changed.

**Comment by JosiahWI** [comment]
After the install() for IrrlichtMt, we need to check whether ANDROID is on and add a second install almost identical to the one for IrrlichtMt, with the target native_app_glue and the same export.
