### ISSUE TITLE
Add verbose flag in CI build

### ISSUE THREAD

**Issue by JosiahWI** [minetest/irrlicht#34]
This is a feature request to improve the process of debugging the build system. It's a very easy change, but I'm opening an issue because I can see the counterargument that the build will seem cluttered. Would this be an acceptable change to PR?

**Comment by sfan5** [comment]
You want to change `make` to `make VERBOSE=1` or is there something else?

**Comment by JosiahWI** [comment]
I'm not familiar with make options. I want to do the equivalent of `cmake --build <build_dir> -v`

**Comment by sfan5** [comment]
That would be the equivalent, yes. Sounds fine to me.
(would probably suffice to do this for one of the Linux builds though)
