### ISSUE TITLE
CI script fails if $CXX is an absolute path

### ISSUE THREAD

**Issue by hecktest** [minetest/irrlicht#40]
This line expects that the path starts with x86_64, which is false if it's an absolute path.

https://github.com/minetest/irrlicht/blob/c84d8acff9b089aaf0fb407542f95e8ff8e5dd60/scripts/ci-build-mingw.sh#L6

This results in a puzzling build failure where make can't seem to find any symbol, as the script has downloaded the wrong libs.

**Comment by JosiahWI** [comment]
Can we fix this by instead checking whether the path contains x86_64?

**Comment by sfan5** [comment]
Simpler:
```diff
-[[ "$CXX" == "x86_64-"* ]] && variant=win64 
+[[ "$(basename "$CXX")" == "x86_64-"* ]] && variant=win64 
```
