### ISSUE TITLE
Add cube map support.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/irrlicht#46]
There is currently only `video::ITexture` class, but it is always 2d and it can not be cube map type (saving 6 faces of cube).

I suggest to add something like `video::ITextureCube` that would consist of 6 `video::ITexture` class pointers.

Usecases: all-directional shadow mapping, maybe something else (I don't know).

**Comment by sfan5** [comment]
And where would this class be used? Which Irrlicht functions would support it?
I don't see any immediate utility here even if it's more than just a container class.

**Comment by Andrey2470T** [comment]
As I already said it would be useful for implementing all-directional shadow mapping. You need to do sampling in all 6 sides to build shadows casting from artificial light sources. I am sure it would be used somewhere else as an unified class, e.g for skybox modifying. In Irrlicht you can create only scene::ISceneNode for it, but can not e.g. obtain direct access to its textures and change their size/color format after creating.

**Comment by Andrey2470T** [comment]
Closing as I had mostly wanted to embed this container class for using in #11470, but I decided to implement own.
