### ISSUE TITLE
Hidden virtual function in CIrrNullDevice

### ISSUE THREAD

**Issue by JosiahWI** [minetest/irrlicht#62]
CIrrNullDevice.h declares draw2DImage on line 144. A number of other subclasses (see CIrrGLDevice.h line 151) override this function with a different method signature, resulting in a warning from g++. To my understanding this basically clobbers the one defined in CIrrNullDevice.h, which is probably not intentional behavior, and could theoretically cause unexpected errors.

Edit: Clarification. I've researched this and reproduced a minimal example to prove the concept to myself. What's going on here is that you can't overload across scopes, so trying to call the signatures defined in CNullDevice from a CGLDevice scope will fail, because it resolves to the signature in CGLDevice which "hides" all the signatures you might expect to inherit. One can do `using CNullDevice::draw2DImage;` to bring those signatures into the scope (this will fix the warning). Maybe we don't want to inherit those signatures, but I'm double checking in case this was an oversight.

**Comment by JosiahWI** [comment]
If there's no objection, I will PR a fix to bring all the base class signatures of `draw2DImage` into any of the subclasses that hide them.

**Comment by sfan5** [comment]
I doubt it matters, no need to do anything IMO.
