### ISSUE TITLE
Add EGL DRM backend

### ISSUE THREAD

**Issue by Unesty** [minetest/irrlicht#7]
## Problem

Drawing directly to display is faster that throught Xorg or anything else.

## Solutions

To add it there must be reading input from device node. Also cursor would be needed. 

## Alternatives

fbdev, dumb buffer DRM

## Additional context

It should be easy to add by adding additional framebuffer adding code.

**Comment by nerzhul** [comment]
see my branch with wayland. It works but i have keymap issues :)

**Comment by nerzhul** [comment]
and also there is tiny rendering issues, but i cannot move and use key (i don't know why, if another coredev can take al ook maybe he can understand why MT doesn't care about wayland events...)

**Comment by Unesty** [comment]
> see my branch with wayland. It works but i have keymap issues :)

Your branch feature/wayland doesn't compile.

**Comment by Unesty** [comment]
how to compile Minetest with this irrlicht?

**Comment by sfan5** [comment]
relevant for Wayland: https://github.com/savegame/sailfish-irrlicht

**Comment by Unesty** [comment]
> relevant for Wayland: https://github.com/savegame/sailfish-irrlicht

It is based on QT, which is too big and slow.

**Comment by sfan5** [comment]
We're switching to SDL2 anyway, so we won't be developing any new backends. Not sure if SDL supports this though.

**Comment by Unesty** [comment]
It supports. SDL itself should be stripped and modified to solve synchronization and latency issues.
