### ISSUE TITLE
Corrupted model file hangs Minetest 5.4.1 client upon connection … b3d? more like bad3d!

### ISSUE THREAD

**Issue by erlehmann** [minetest/irrlicht#70]
##### Minetest version
5.4.1

##### OS / Hardware
Operating system: GNU/Linux

##### Summary
A corrupted B3D model found by using AFL on the Irrlicht hello world example code (example 1) in like 10 minutes or so of fuzzing is able to stall Minetest 5.4.1 forever upon connecting to a server that delivers it.

If you want to do this yourself, note that both the model `ninja.b3d` and the example code were removed recently from irrlichtmt by @hecktest, but they are still in the git history of course.

##### Steps to reproduce
0. Download attached bad3d mod.
1. Create a new world.
2. Enable bad3d mod.
3. Connect to server.
4. Wait a long time.
5. Send SIGTERM to Minetest, as it is very good at not dying while hanging.

[bad3d.zip](https://github.com/minetest/minetest/files/7180153/bad3d.zip)

**Comment by erlehmann** [comment]
> <sfan5> it indeed still happens on 5.5

**Comment by erlehmann** [comment]
> <luatic> This is interesting. I had to try modlib's B3D reader (which is written in Lua) at it, and it crashed as expected. It seems the file contains a chunk of invalid type. I suppose Irrlicht doesn't handle this case.

**Comment by appgurueu** [comment]
This is interesting. I had to try modlib's B3D reader (which is written in Lua) at it, and it crashed as expected. It seems the file contains a chunk of invalid type. I suppose Irrlicht doesn't handle this case.
