### ISSUE TITLE
#77 breaks loading of some models (notably most NSSM models)

### ISSUE THREAD

**Issue by lhofhansl** [minetest/irrlicht#88]
Turns out that #77 breaks model loading for some models (most NSSM models for example).
I'd suggest we revert that one until we figure out what the problem is.

@x2048 in case you wanted to have a look.

**Comment by lhofhansl** [comment]
Not sure what the one "thumbs down" is all about. It's clearly something that needs to be fixed.
I created a PR for the revert.

**Comment by x2048** [comment]
IIRC #77 is only invoked if MT detects normals pointing inward.

I only tested with MCL2 b3d models, and I can check with .x from NSSM.

**Comment by lhofhansl** [comment]
It does not happen with all .x models. Not sure what makes the difference. If it helps I can post one of the models where it breaks.

**Comment by sfan5** [comment]
Closing favor of the issue on MT.
