### ISSUE TITLE
Commit 7d1dc8b2d54ada305e4e2caa38debf35a171c52d looks sus

### ISSUE THREAD

**Issue by erlehmann** [minetest/irrlicht#94]
This commit is titled “ Get rid of ancient workaround ...that probably negatively impacted performance or something else”: https://github.com/minetest/irrlicht/commit/7d1dc8b2d54ada305e4e2caa38debf35a171c52d

As far as I can tell, the code that was removed followed the recommendations from this article:
https://docs.microsoft.com/en-us/windows/win32/dxtecharts/game-timing-and-multicore-processors

> 3. Compute all timing on a single thread. Computation of timing on multiple threads — for example, with each thread associated with a specific processor — greatly reduces performance of multi-core systems.
> 
> 4. Set that single thread to remain on a single processor by using the Windows API SetThreadAffinityMask. Typically, this is the main game thread. While QueryPerformanceCounter and QueryPerformanceFrequency typically adjust for multiple processors, bugs in the BIOS or drivers may result in these routines returning different values as the thread moves from one processor to another. So, it's best to keep the thread on a single processor.

I think it would be a good idea to either explain why the code was removed or revert commit 7d1dc8b2d54ada305e4e2caa38debf35a171c52d.

**Comment by erlehmann** [comment]
I have now researched this for much too long.

It seems that removing the code is going to cause timer bugs on multicore systems.

I am writing on a system where even though the processors should tick the same, Linux found a delta:

```
[    0.351568] TSC synchronization [CPU#0 -> CPU#1]:
[    0.351568] Measured 521224 cycles TSC warp between CPUs, turning off TSC clock.
[    0.351568] tsc: Marking TSC unstable due to check_tsc_sync_source failed
```

Note that this is a system which advertises itself as constant TSC – i.e. processors should tick the same.

I have not found *any* supporting evidence that commit 7d1dc8b2d54ada305e4e2caa38debf35a171c52d is justified. I think it should be reverted.

**Comment by sfan5** [comment]
As for "why": I estimate that the performance impact of setting the affinity mask (therefore potentially rescheduling the thread) every time the timer is retrieved can be quite severe.

The article is interesting but I don't trust it to accurately report the situation today or even 10 years ago\*.
And lastly, Minetest internally uses `QueryPerformanceCounter` without<b>(!)</b> this workaround and nobody has ever noticed anything broken.

\* see also this which explicitly mentions multicore bugs in a section about W2003 & WinXP: https://docs.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps

**Comment by erlehmann** [comment]
> As for "why": I estimate that the performance impact of setting the affinity mask (therefore potentially rescheduling the thread) every time the timer is retrieved can be quite severe.

The documentation at https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setthreadaffinitymask says:

> If the new thread affinity mask does not specify the processor that is currently running the thread, the thread is rescheduled on one of the allowable processors.

Since the affinity mask is always `1` in the code that you removed, I see why this is suboptimal.

> The article is interesting but I don't trust it to accurately report the situation today or even 10 years ago*.

As far as I can tell, the article was published 2018-05-31.

I have since dug more into the behaviour of system timers. It seems that on Core Duo and earlier Intel systems not having the timing workaround can *definitely* mess up timing on Windows if the thread is not pinned to a core.

Now you may say that these systems are old. That is correct! Core Duo was introduced around 2006. What is much more worrying to me is newer systems: AMD K8 multicore systems – discontinued in 2014 – for example, have timers that are tied to clock cycles, meaning that power management features would mess up timers that are not pinned to a core. I have read that gamers even use an application to keep their core timings in sync to work around this …

Even newer systems can have timer bugs in these circumstances – but those I know about do not run Windows.

> Minetest internally uses QueryPerformanceCounter without(!) this workaround and nobody has ever noticed anything broken.

Given what I know about timers (very little), the effect of this would probably be worse performance than expected on multicore Windows systems. Given that I have an affected multicore system, I could test it with ReactOS (assuming timers behave similarly).

@sfan5 I can not promise anything, but if you could point me to a Win32 binaries (without and with this patch), I can maybe try to figure out the performance implications of this patch. It would also help to figure out if this indeed makes Minetest faster on Windows.
