### ISSUE TITLE
OpenGL preference policy; prefer GLVND at or above CMake 3.11

### ISSUE THREAD

**Issue by JosiahWI** [minetest/irrlicht#95]
My proposed change is to remove the Legacy OpenGL preference in the CMake build, and set policy CMP0072. The simplest way to do it would be to increase the version range to include 3.11, so that the policy will be chosen automatically as described by https://cmake.org/cmake/help/latest/policy/CMP0072.html. None of the policies introduced by CMake 3.10 (CMP0070, CMP0071) affect us, and CMP0072 was the only policy introduced in CMake 3.11, so there will be no unexpected side effects of increasing the version range.

Relevant Minetest issue: minetest/minetest#12041

Edit: Won't cause a regression of minetest/minetest#7665; could cause a regression of https://github.com/minetest/minetest/pull/7655#issuecomment-414150525 depending on the CMake version on that system. This is not a trivial configuration change.

**Comment by sfan5** [comment]
This is just a guess but 074e81f78f4daa1c1da739a7ae0b0ef507ec06ee could affect this issue positively (making it no longer happen).

**Comment by sfan5** [comment]
Can you prepare a PR?
