### ISSUE TITLE
SDL2 header not found on Mac OS

### ISSUE THREAD

**Issue by JosiahWI** [minetest/irrlicht#96]
The header includes <SDL2/SDL.h> and this seemed to work for me on Debian Linux, but maybe I didn't enable SDL2 correctly. The Discord user who reported the issue confirmed that the include path CMake sets points directly to the SDL2 directory, which would explain why this include doesn't work.

**Comment by sfan5** [comment]
The paths are pulled directly from the SDL2 cmake config:
https://github.com/minetest/irrlicht/blob/4fb1c55ec53ef32654fc7cfe60419e93bc3072b8/source/Irrlicht/CMakeLists.txt#L85-L86

No idea if these are supposed to point to SDL.h or the parent folder. A quick google suggests the latter.

**Comment by JosiahWI** [comment]
The include path pointed to `$SDL_DIR/include/SDL2/` and the build failed with a missing `<SDL2/SDL.h>`. I don't know why it doesn't work, and I cannot test it, so I'm documenting it in this issue. Building with the SDL2 driver is broken on Mac OS.
