### ISSUE TITLE
Readd Directx render.

### ISSUE THREAD

**Issue by IrrlichtMt4** [minetest/irrlicht#97]
Readd DirectX render. Readding the DirectX renderer could improve the rendering on some devices. Also DirectX is faster on some devices.

**Comment by sfan5** [comment]
Having another renderer would double the amount of work needed to maintain it or add new features. We also don't have anyone knowledgeable in DirectX, in fact we only have one or two developers who even use Windows.

**Comment by v-rob** [comment]
Most of our performance problems aren't actually OpenGL vs DirectX--they're problems due to bad graphics code design.  If we focus on improving Minetest's rendering code, then we'll get much larger performance boosts than the small ones we'd get from DirectX optimizations.

**Comment by IrrlichtMt4** [comment]
Thanks for reviewing. It makes sense that the DirectX renderer was removed. Thanks for explaining :)
